name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # checks out repository
      - name: Use Node

        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run : npm install
      
      - name: Run Build
        run: npm run build --if-present

      - name: Run test
        run : npm test
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 'b62b0e9f-1314-438f-9d36-2a73d5f07bbc'
          heroku_app_name: 'online-soccer'
          heroku_email: 'aniketkud22@gmail.com'


